# The native core's Kotlin bindings (generated by UniFFI) reach Rust through JNA, which finds methods, callbacks and
# structures by reflection. R8 must not rename or drop them.
-keep class com.sun.jna.** { *; }
-keep class * implements com.sun.jna.** { *; }
-keep class harness.codegraff.android.core.** { *; }
-dontwarn java.awt.**
